### ISSUE TITLE
Search functionality needs to be patient

### ISSUE THREAD

**Issue by ajeanmahoney** [ietf-authors/authors.ietf.org#14]
Pausing before I finish typing a term in the search field causes "Unexpected Error Occurred" and "No pages matching your query" messages. Actually, I can't seem to type fast enough to avoid the messages; however, if I keep typing, I can get search results.  For example, "seriesInfo" does not produce search results until I finish typing it, which means adding either a space ("seriesInfo ") or an angle bracket after ("seriesInfo>").

**Comment by JayDaley** [comment]
I will escalate this.

**Comment by JayDaley** [comment]
Fixed - for details see #21
